Javascript documentation
matchmore/documentation pull request #5
Opened 2018-06-06 11:13 UTC by lmlynik

2018-06-06 11:47 UTC, elsener commented on javaScript.md
> +Setup application API key and world, get it for free from [http://matchmore.io/](http://matchmore.io/).
should be https?

2018-06-06 11:57 UTC, wenjdu requested changes
It is a great one, 
good job Lukasz !!

2018-06-06 11:57 UTC, wenjdu commented on javaScript.md
> +                            20 /* s */,
I like how you added the / m and s . I will keep this idea for the other sdks comment.

2018-06-06 11:57 UTC, wenjdu commented on javaScript.md
> +First you need to create the main device, first device you create is the main device
The sentence is repeated.

2018-06-06 11:57 UTC, wenjdu commented on javaScript.md
> +await manager.createMobileDevice("me", "iOS", "");
add the hint for the third parameter - deviceToken

2018-06-06 11:57 UTC, wenjdu commented on javaScript.md
> +let newDevice = await manager.createMobileDevice("another mobile", "android");
third parameter about fcm and apns ?

2018-06-12 13:42 UTC, wenjdu approved these changes

2018-06-12 13:43 UTC, wenjdu commented
Nicely done @lmlynik ! I am merging this.

2018-06-12 13:43 UTC, merged